# Generated by Django 2.1 on 2018-08-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
