# Generated by Django 2.1 on 2018-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180804_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='contato',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
